name: flutter_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner:
  flutter_bloc: ^8.0.1
  gap: ^3.0.1
  flutter_modular: 6.1.0
  dart_mappable: ^3.2.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  dart_mappable_builder:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  bloc_test: ^9.1.0
  mocktail: ^1.0.1
flutter:
  uses-material-design: true
